version: "3.8"

services:
  web:
    image: load-balanced-app
    build:
      context: .
    deploy:
      replicas: 3
    environment:
      - HOSTNAME=${HOSTNAME:-"default"}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
